version: "3"

services:
  backend:
    build:
      context: ./custom-frappe
      args:
        FRAPPE_BRANCH: version-15
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               /home/frappe/.local/bin/bench serve --port 8000"
    depends_on:
      - db
      - redis-cache
      - redis-queue

  configurator:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: "no"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               /home/frappe/.local/bin/bench set-config -g db_host db &&
               /home/frappe/.local/bin/bench set-config -gp db_port 3306 &&
               /home/frappe/.local/bin/bench set-config -g redis_cache redis://redis-cache:6379 &&
               /home/frappe/.local/bin/bench set-config -g redis_queue redis://redis-queue:6379 &&
               /home/frappe/.local/bin/bench set-config -g redis_socketio redis://redis-queue:6379 &&
               /home/frappe/.local/bin/bench set-config -gp socketio_port 9000"
    depends_on:
      - db
      - redis-cache
      - redis-queue

  create-site:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: "no"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               wait-for-it -t 120 db:3306 &&
               wait-for-it -t 120 redis-cache:6379 &&
               wait-for-it -t 120 redis-queue:6379 &&
               sleep 5 &&
               /home/frappe/.local/bin/bench new-site frontend --mariadb-root-username=root --mariadb-root-password=admin --admin-password=admin --no-mariadb-socket"
    depends_on:
      configurator:
        condition: service_completed_successfully

  db:
    image: mariadb:10.6
    networks:
      - frappe_network
    healthcheck:
      test: mysqladmin ping -h localhost --password=admin
      interval: 1s
      retries: 20
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - db-data:/var/lib/mysql

  frontend:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: unless-stopped
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               sudo nginx -g 'daemon off;'"
    environment:
      BACKEND: backend:8000
      FRAPPE_SITE_NAME_HEADER: frontend
      SOCKETIO: websocket:9000
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    ports:
      - "8080:80"
    depends_on:
      - backend
      - websocket

  queue-short:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: unless-stopped
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               /home/frappe/.local/bin/bench worker --queue short"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - configurator

  queue-long:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: unless-stopped
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               /home/frappe/.local/bin/bench worker --queue long"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - configurator

  scheduler:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: unless-stopped
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               /home/frappe/.local/bin/bench schedule"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - configurator

  websocket:
    image: custom-frappe:latest
    networks:
      - frappe_network
    restart: unless-stopped
    command: >
      bash -c "cd /home/frappe/frappe-bench &&
               node apps/frappe/socketio.js"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
      - logs:/home/frappe/frappe-bench/logs
    depends_on:
      - configurator

  redis-queue:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped
    volumes:
      - redis-queue-data:/data

  redis-cache:
    image: redis:6.2-alpine
    networks:
      - frappe_network
    restart: unless-stopped

volumes:
  db-data:
  redis-queue-data:
  sites:
  logs:

networks:
  frappe_network:
    driver: bridge 